Fix filby permissions Check for test containers to be ready

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,6 +3,25 @@
 npm run lint-staged
 docker compose down
 npm run docker
+containers=("fby_js_example" "fby_ts_example" "fby_test")
+for container in "${containers[@]}"; do
+  attempts=1
+  max=5
+  for i in {0..5}; do
+    echo "Checking ${container} ${attempts}/${max}"
+    if docker exec "$container" pg_isready -U fby_example; then
+      break
+    else
+      sleep 1
+      ((attempts++))
+    fi
+  done
+
+  if [ "$attempts" -gt 5 ]; then
+    echo "Connection to ${container} failed after ${max} retries"
+    exit 1
+  fi
+done
 pushd examples/javascript && npm test && popd
 pushd examples/typescript && npm test && popd
 npm test
